(function(){
  'use strict';
  var view=document.getElementById('view'),title=document.getElementById('title'),back=document.getElementById('backButton'),flash=document.getElementById('flash');
  var config=null,current=null,currentExercise=0,timerReturn=null,audioContext=null;
  function esc(s){return String(s===undefined?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function dateText(iso){var d=new Date(iso);return ('0'+d.getDate()).slice(-2)+'/'+('0'+(d.getMonth()+1)).slice(-2)+'/'+d.getFullYear();}
  function show(name,html,canBack){title.innerHTML=name;view.innerHTML=html;back.className=canBack?'back':'back hidden';window.scrollTo(0,0);}
  function bind(id,event,fn){var el=document.getElementById(id);if(el){el.addEventListener(event,fn,false);}}
  function home(){current=null;show('GYM CONSOLE','<div class="menu"><button class="workout" id="startA">ALLENAMENTO A</button><button class="workout" id="startB">ALLENAMENTO B</button><button id="history">STORICO</button><button id="progress">PROGRESSI</button><button class="timer-menu" id="freeTimer">TIMER LIBERO</button><button id="settings">IMPOSTAZIONI</button></div>',false);bind('startA','click',function(){startWorkout('A');});bind('startB','click',function(){startWorkout('B');});bind('history','click',history);bind('progress','click',progress);bind('freeTimer','click',function(){timerReturn=home;timerScreen();});bind('settings','click',settings);}
  function startWorkout(kind){var w=config.workouts[kind],settings=GymStorage.settings(),i,count;current={id:'s-'+new Date().getTime(),date:new Date().toISOString(),kind:kind,name:w.name,notes:'',completed:false,exercises:[]};for(i=0;i<w.exercises.length;i++){count=w.exercises[i].sets;if(count===3&&settings.mainSets===2){count=2;}current.exercises.push({id:w.exercises[i].id,name:w.exercises[i].name,resistance:w.exercises[i].resistance,load:'',sets:(function(){var a=[],j;for(j=0;j<count;j++){a.push({reps:'',done:false,skipped:false});}return a;}())});}currentExercise=0;exerciseScreen();}
  function resistanceField(ex,saved){if(ex.resistance==='band'){return '<select id="resistance"><option value="15 kg">Elastico 15 kg</option><option value="20 kg">Elastico 20 kg</option><option value="">Scegli elastico</option></select>';}if(ex.resistance==='body'){return '<select id="resistance"><option value="Corpo libero">Corpo libero</option></select>';}return '<input id="load" type="number" inputmode="decimal" min="0" step="0.5" value="'+esc(saved.load)+'"> kg';}
  function exerciseScreen(){var w=config.workouts[current.kind],ex=w.exercises[currentExercise],saved=current.exercises[currentExercise],i,rows='',last=findLast(ex.id);for(i=0;i<saved.sets.length;i++){rows+='<div class="set-row"><strong>Serie '+(i+1)+'</strong><input id="reps'+i+'" type="number" inputmode="numeric" min="0" value="'+esc(saved.sets[i].reps)+'" aria-label="Ripetizioni serie '+(i+1)+'"><span>'+((saved.sets[i].done)?'<span class="done-mark">✓ FATTA</span>':(saved.sets[i].skipped?'<span class="muted">SALTATA</span>':'ripetizioni'))+'</span></div>';}
    show(current.name,'<div class="card"><div class="muted">ESERCIZIO '+(currentExercise+1)+' DI '+w.exercises.length+'</div><h2>'+esc(ex.name)+'</h2><div class="technique">'+esc(ex.tip)+'</div><div class="stats"><span><b>'+saved.sets.length+'</b> serie</span><span><b>'+ex.min+'-'+ex.max+'</b> rip.</span><span><b>'+ex.rest+' s</b> recupero</span></div></div>'+(last?'<div class="status small">Ultima volta: <b>'+esc(last.load||last.resistance)+'</b> · '+esc(last.reps.join(' / '))+'</div>':'')+'<div class="card"><div class="field"><label>RESISTENZA / CARICO</label>'+resistanceField(ex,saved)+'</div>'+rows+'<div class="actions"><button class="complete" id="completeSet">SERIE COMPLETATA</button><button id="skipSet">SALTA SERIE</button></div></div><div class="nav-row"><button id="prev">‹ PRECEDENTE</button><button id="next">SUCCESSIVO ›</button></div><button id="finish" class="danger" style="width:100%">TERMINA ALLENAMENTO</button>',true);restoreResistance(ex,saved);bindInputs(saved);bind('completeSet','click',completeSet);bind('skipSet','click',skipSet);bind('prev','click',function(){saveFields();if(currentExercise>0){currentExercise--;exerciseScreen();}});bind('next','click',function(){saveFields();if(currentExercise<w.exercises.length-1){currentExercise++;exerciseScreen();}else{finishWorkout();}});bind('finish','click',finishWorkout);back.onclick=function(){if(confirm('Uscire? I dati non ancora terminati non saranno salvati.')){home();}};}
  function restoreResistance(ex,saved){var el=document.getElementById('resistance');if(el&&saved.load){el.value=saved.load;}}
  function bindInputs(saved){var i;for(i=0;i<saved.sets.length;i++){(function(n){bind('reps'+n,'change',function(){saved.sets[n].reps=this.value;});}(i));}}
  function saveFields(){var saved=current.exercises[currentExercise],el=document.getElementById('load')||document.getElementById('resistance'),i;if(el){saved.load=el.value;}for(i=0;i<saved.sets.length;i++){el=document.getElementById('reps'+i);if(el){saved.sets[i].reps=el.value;}}}
  function pendingSet(){var sets=current.exercises[currentExercise].sets,i;for(i=0;i<sets.length;i++){if(!sets[i].done&&!sets[i].skipped){return i;}}return -1;}
  function completeSet(){var n=pendingSet(),input;if(n<0){alert('Tutte le serie sono già registrate.');return;}saveFields();input=document.getElementById('reps'+n);if(!current.exercises[currentExercise].sets[n].reps){if(input){input.focus();}alert('Inserisci prima le ripetizioni.');return;}prepareAudio();current.exercises[currentExercise].sets[n].done=true;timerReturn=exerciseScreen;GymTimer.start(config.workouts[current.kind].exercises[currentExercise].rest);timerScreen();}
  function skipSet(){var n=pendingSet();if(n>=0){saveFields();current.exercises[currentExercise].sets[n].skipped=true;exerciseScreen();}}
  function finishWorkout(){saveFields();if(!confirm('Terminare e salvare questo allenamento?')){return;}current.completed=true;current.notes=prompt('Note allenamento (facoltative):','')||'';GymStorage.addSession(current);alert('Allenamento salvato.');home();}
  function timerScreen(){var s=GymTimer.seconds();show('TIMER','<div class="timer-box"><div id="countdown" class="countdown">'+formatTime(s)+'</div><div id="timerState" class="muted">'+(GymTimer.isRunning()?'IN CORSO':'PRONTO')+'</div><div class="timer-buttons"><button data-seconds="30">30 s</button><button data-seconds="60">60 s</button><button data-seconds="90">90 s</button><button data-seconds="120">120 s</button><button id="add15">+15 s</button><button id="pause">PAUSA</button><button id="reset">RESET</button><button id="skipTimer">SALTA</button></div></div>',true);var buttons=view.getElementsByTagName('button'),i;for(i=0;i<buttons.length;i++){if(buttons[i].getAttribute('data-seconds')){buttons[i].onclick=function(){prepareAudio();GymTimer.start(this.getAttribute('data-seconds'));};}}bind('add15','click',function(){prepareAudio();GymTimer.add(15);});bind('pause','click',function(){prepareAudio();if(GymTimer.isRunning()){GymTimer.pause();this.innerHTML='RIPRENDI';}else{GymTimer.resume();this.innerHTML='PAUSA';}});bind('reset','click',function(){GymTimer.reset();});bind('skipTimer','click',function(){GymTimer.skip();if(timerReturn){timerReturn();}});back.onclick=function(){if(timerReturn){timerReturn();}else{home();}};}
  function formatTime(s){var m=Math.floor(s/60),r=s%60;return ('0'+m).slice(-2)+':'+('0'+r).slice(-2);}
  function timerTick(s,running){var el=document.getElementById('countdown'),st=document.getElementById('timerState');if(el){el.innerHTML=formatTime(s);}if(st){st.innerHTML=running?'IN CORSO':'IN PAUSA';}}
  function timerDone(){beep();try{if(navigator.vibrate){navigator.vibrate([400,150,400]);}}catch(e){}flash.className='flash';setTimeout(function(){flash.className='flash hidden';},3000);}
  function prepareAudio(){try{var C=window.AudioContext||window.webkitAudioContext;if(!C){return;}if(!audioContext){audioContext=new C();}if(audioContext.state==='suspended'&&audioContext.resume){audioContext.resume();}}catch(e){}}
  function beep(){try{var o,g;if(!audioContext){return;}if(audioContext.state==='suspended'&&audioContext.resume){audioContext.resume();}o=audioContext.createOscillator();g=audioContext.createGain();o.connect(g);g.connect(audioContext.destination);o.frequency.value=880;g.gain.value=0.5;o.start(0);setTimeout(function(){try{o.stop(0);}catch(e){}},700);}catch(e){}}
  function findLast(id){var sessions=GymStorage.read().sessions,i,j,s,e;for(i=sessions.length-1;i>=0;i--){s=sessions[i];for(j=0;j<s.exercises.length;j++){e=s.exercises[j];if(e.id===id){return {load:e.load,resistance:e.load,reps:(function(){var a=[],k;for(k=0;k<e.sets.length;k++){if(e.sets[k].done){a.push(e.sets[k].reps);}}return a;}())};}}}return null;}
  function history(){var d=GymStorage.read(),html='<h2>Storico</h2>',i,s;if(!d.sessions.length){html+='<div class="card">Nessun allenamento salvato.</div>';}for(i=d.sessions.length-1;i>=0;i--){s=d.sessions[i];html+='<button class="history-item" data-index="'+i+'">'+dateText(s.date)+' — '+esc(s.name)+'</button>';}show('STORICO',html,true);var b=view.getElementsByTagName('button');for(i=0;i<b.length;i++){b[i].onclick=function(){historyDetail(parseInt(this.getAttribute('data-index'),10));};}back.onclick=home;}
  function historyDetail(index){var s=GymStorage.read().sessions[index],html='<h2>'+dateText(s.date)+' — '+esc(s.name)+'</h2>',i,j,e,reps;for(i=0;i<s.exercises.length;i++){e=s.exercises[i];reps=[];for(j=0;j<e.sets.length;j++){if(e.sets[j].done){reps.push(e.sets[j].reps);}}html+='<div class="card"><h3>'+esc(e.name)+'</h3><div>'+esc(e.load||'—')+' · '+esc(reps.join(' / ')||'Nessuna serie')+'</div></div>';}if(s.notes){html+='<div class="card">Note: '+esc(s.notes)+'</div>';}show('DETTAGLIO',html,true);back.onclick=history;}
  function progress(){var all=[],k,w,i,last,html='<h2>Ultime prestazioni</h2>';for(k in config.workouts){if(config.workouts.hasOwnProperty(k)){w=config.workouts[k];for(i=0;i<w.exercises.length;i++){if(!contains(all,w.exercises[i].id)){all.push(w.exercises[i].id);last=findLast(w.exercises[i].id);html+='<div class="card"><h3>'+esc(w.exercises[i].name)+'</h3>'+(last?'<div>'+esc(last.load||last.resistance)+' · '+esc(last.reps.join(' / '))+'</div>'+suggestion(w.exercises[i],last):'<div class="muted">Nessun dato</div>')+'</div>';}}}}show('PROGRESSI',html,true);back.onclick=home;}
  function contains(a,v){var i;for(i=0;i<a.length;i++){if(a[i]===v){return true;}}return false;}
  function suggestion(ex,last){var i;if(last.reps.length<ex.sets){return '';}for(i=0;i<last.reps.length;i++){if(parseInt(last.reps[i],10)<ex.max){return '';}}return '<div class="hint small">Prossima volta prova ad aumentare il carico.</div>';}
  function settings(){var d=GymStorage.read(),n=d.settings.mainSets||3;show('IMPOSTAZIONI','<div class="card"><h3>Prime due settimane</h3><label><select id="mainSets"><option value="3">3 serie principali</option><option value="2">2 serie principali</option></select></label></div><div class="actions"><button id="export">ESPORTA DATI</button><button id="import">IMPORTA DATI</button></div><input id="fileInput" class="hidden" type="file" accept="application/json"><div class="small muted">I dati restano soltanto su questo dispositivo. Fai periodicamente un backup.</div>',true);document.getElementById('mainSets').value=String(n);bind('mainSets','change',function(){var s=GymStorage.settings();s.mainSets=parseInt(this.value,10);GymStorage.settings(s);});bind('export','click',exportData);bind('import','click',function(){document.getElementById('fileInput').click();});bind('fileInput','change',importData);back.onclick=home;}
  function exportData(){var text=JSON.stringify(GymStorage.read(),null,2),blob,url,a;try{blob=new Blob([text],{type:'application/json'});url=(window.URL||window.webkitURL).createObjectURL(blob);a=document.createElement('a');a.href=url;a.download='gym-console-backup.json';document.body.appendChild(a);a.click();document.body.removeChild(a);setTimeout(function(){(window.URL||window.webkitURL).revokeObjectURL(url);},1000);}catch(e){prompt('Copia e salva questo backup:',text);}}
  function importData(evt){var file=evt.target.files[0],reader;if(!file){return;}reader=new FileReader();reader.onload=function(){var data;try{data=JSON.parse(reader.result);if(!data.sessions||!data.settings){throw new Error();}if(confirm('Sostituire tutti i dati attuali con il backup?')){GymStorage.replace(data);alert('Importazione completata.');settings();}}catch(e){alert('File di backup non valido.');}};reader.readAsText(file);}
  GymTimer.configure(timerTick,timerDone);
  GymWorkouts.load(function(data){config=data;home();});
  if('serviceWorker' in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('service-worker.js');},false);}
}());
