(function(){
  'use strict';
  var APP_VERSION='3.0.0',APP_DATE='25/08/2026';
  var view=document.getElementById('view'),title=document.getElementById('title'),back=document.getElementById('backButton'),flash=document.getElementById('flash');
  var config=null,current=null,currentExercise=0,timerReturn=null,audioContext=null,lastAnnounced=-1,updateReady=false,registration=null;

  function esc(s){return String(s===undefined?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function dateText(iso){var d=new Date(iso);return ('0'+d.getDate()).slice(-2)+'/'+('0'+(d.getMonth()+1)).slice(-2)+'/'+d.getFullYear();}
  function show(name,html,canBack){title.innerHTML=name;view.innerHTML=html;back.className=canBack?'back':'back hidden';window.scrollTo(0,0);}
  function bind(id,event,fn){var el=document.getElementById(id);if(el){el.addEventListener(event,fn,false);}}
  function contains(a,v){var i;for(i=0;i<a.length;i++){if(a[i]===v){return true;}}return false;}
  function updateNotice(){return updateReady?'<div class="update-banner">NUOVA VERSIONE DISPONIBILE <button id="applyUpdate">AGGIORNA ORA</button></div>':'';}
  function bindUpdate(){bind('applyUpdate','click',applyUpdate);}

  function home(){var draft=GymStorage.draft(),resume='';current=null;if(draft){resume='<div class="card resume-card"><h3>Allenamento interrotto</h3><div class="small muted">'+esc(draft.name)+' · '+dateText(draft.date)+'</div><div class="actions"><button id="resumeWorkout">RIPRENDI ALLENAMENTO</button><button id="deleteDraft" class="danger">ELIMINA BOZZA</button></div></div>';}
    show('GYM CONSOLE',updateNotice()+resume+'<div class="menu"><button class="workout" id="startA">ALLENAMENTO A</button><button class="workout" id="startB">ALLENAMENTO B</button><button id="history">STORICO</button><button id="progress">PROGRESSI</button><button class="timer-menu" id="freeTimer">TIMER LIBERO</button><button id="settings">IMPOSTAZIONI</button></div>',false);bindUpdate();bind('resumeWorkout','click',resumeWorkout);bind('deleteDraft','click',function(){if(confirm('Eliminare definitivamente l’allenamento interrotto?')){GymStorage.draft(null);home();}});bind('startA','click',function(){startWorkout('A');});bind('startB','click',function(){startWorkout('B');});bind('history','click',history);bind('progress','click',progress);bind('freeTimer','click',function(){timerReturn=home;timerScreen();});bind('settings','click',settings);}

  function startWorkout(kind){var w=config.workouts[kind],settings=GymStorage.settings(),i,j,count,last,sets;if(GymStorage.draft()&&!confirm('Esiste già un allenamento interrotto. Sostituirlo con uno nuovo?')){return;}current={id:'s-'+new Date().getTime(),date:new Date().toISOString(),kind:kind,name:w.name,notes:'',completed:false,currentExercise:0,introDone:false,exercises:[]};for(i=0;i<w.exercises.length;i++){count=w.exercises[i].sets;if(count===3&&settings.mainSets===2){count=2;}sets=[];for(j=0;j<count;j++){sets.push({reps:'',done:false,skipped:false});}last=findLast(w.exercises[i].id);current.exercises.push({id:w.exercises[i].id,name:w.exercises[i].name,resistance:w.exercises[i].resistance,load:last?last.load:'',notes:'',sets:sets});}currentExercise=0;saveDraft();workoutIntro();}
  function resumeWorkout(){current=GymStorage.draft();if(!current){home();return;}currentExercise=current.currentExercise||0;if(current.introDone){exerciseScreen();}else{workoutIntro();}}
  function saveDraft(){if(current){current.currentExercise=currentExercise;GymStorage.draft(current);}}
  function leaveWorkout(){saveFields();saveDraft();if(confirm('Uscire dalla sessione? La bozza resterà salvata e potrai riprenderla dalla Home.')){home();}}

  function workoutIntro(){var w=config.workouts[current.kind],html='<div class="card"><h2>Riscaldamento</h2><p>'+esc(w.warmup)+'</p><button id="warmupTimer" class="primary" style="width:100%">AVVIA TIMER 8 MINUTI</button></div><div class="card"><h3>Panoramica</h3><ol class="overview">',i,ex;for(i=0;i<w.exercises.length;i++){ex=w.exercises[i];html+='<li><b>'+esc(ex.name)+'</b><br><span class="small muted">'+current.exercises[i].sets.length+' × '+ex.min+'-'+ex.max+(ex.unit?' '+esc(ex.unit):'')+' · '+ex.rest+' s</span></li>';}html+='</ol></div><button id="beginWorkout" class="complete" style="width:100%">INIZIA ALLENAMENTO</button>';show(current.name,html,true);bind('warmupTimer','click',function(){prepareAudio();lastAnnounced=-1;timerReturn=workoutIntro;GymTimer.start(480);timerScreen();});bind('beginWorkout','click',function(){current.introDone=true;saveDraft();exerciseScreen();});back.onclick=leaveWorkout;}

  function resistanceField(ex,saved){if(ex.resistance==='band'){return '<select id="resistance"><option value="">Scegli elastico</option><option value="15 kg">Elastico 15 kg</option><option value="20 kg">Elastico 20 kg</option></select>';}if(ex.resistance==='body'){return '<select id="resistance"><option value="Corpo libero">Corpo libero</option></select>';}return '<input id="load" type="number" inputmode="decimal" min="0" step="0.5" value="'+esc(saved.load)+'"> kg';}
  function exerciseScreen(){var w=config.workouts[current.kind],ex=w.exercises[currentExercise],saved=current.exercises[currentExercise],i,rows='',last=findLast(ex.id),pct=Math.round((currentExercise/w.exercises.length)*100);for(i=0;i<saved.sets.length;i++){rows+='<div class="set-row"><strong>Serie '+(i+1)+'</strong><input id="reps'+i+'" type="number" inputmode="numeric" min="0" value="'+esc(saved.sets[i].reps)+'" aria-label="Ripetizioni serie '+(i+1)+'"><span>'+((saved.sets[i].done)?'<span class="done-mark">✓ FATTA</span>':(saved.sets[i].skipped?'<span class="muted">SALTATA</span>':'rip.'))+'</span>'+(saved.sets[i].done||saved.sets[i].skipped?'<button class="edit-set" data-edit="'+i+'">MODIFICA</button>':'')+'</div>';}
    show(current.name,updateNotice()+'<div class="card"><div class="muted">ESERCIZIO '+(currentExercise+1)+' DI '+w.exercises.length+'</div><div class="progress-track"><i style="width:'+pct+'%"></i></div><h2>'+esc(ex.name)+'</h2><div class="technique">'+esc(ex.tip)+'</div><div class="stats"><span><b>'+saved.sets.length+'</b> serie</span><span><b>'+ex.min+'-'+ex.max+'</b> '+esc(ex.unit||'rip.')+'</span><span><b>'+ex.rest+' s</b> recupero</span></div></div>'+(last?'<div class="status small">Ultima volta: <b>'+esc(last.load||'—')+'</b> · '+esc(last.reps.join(' / '))+'</div>':'')+'<div class="card"><div class="field"><label>RESISTENZA / CARICO</label>'+resistanceField(ex,saved)+'</div>'+rows+'<div class="field" style="width:100%"><label>NOTE ESERCIZIO</label><textarea id="exerciseNotes" placeholder="Tecnica, sensazioni, variante...">'+esc(saved.notes||'')+'</textarea></div><div class="actions"><button class="complete" id="completeSet">SERIE COMPLETATA</button><button id="skipSet">SALTA SERIE</button>'+(ex.timer?'<button id="exerciseTimer">TIMER '+ex.min+' s</button>':'')+'<button id="finishExercise">TERMINA ESERCIZIO</button></div></div><div class="nav-row"><button id="prev">‹ PRECEDENTE</button><button id="next">SUCCESSIVO ›</button></div><button id="finish" class="danger" style="width:100%">TERMINA ALLENAMENTO</button>',true);restoreResistance(saved);bindInputs(saved);bindEditButtons(saved);bindUpdate();bind('completeSet','click',completeSet);bind('skipSet','click',skipSet);bind('exerciseTimer','click',function(){saveFields();prepareAudio();lastAnnounced=-1;timerReturn=exerciseScreen;GymTimer.start(ex.min);timerScreen();});bind('finishExercise','click',finishExercise);bind('prev','click',function(){saveFields();if(currentExercise>0){currentExercise--;saveDraft();exerciseScreen();}});bind('next','click',function(){saveFields();if(currentExercise<w.exercises.length-1){currentExercise++;saveDraft();exerciseScreen();}else{finishWorkout();}});bind('finish','click',finishWorkout);back.onclick=leaveWorkout;}
  function restoreResistance(saved){var el=document.getElementById('resistance');if(el&&saved.load){el.value=saved.load;}}
  function bindInputs(saved){var i,load=document.getElementById('load')||document.getElementById('resistance'),notes=document.getElementById('exerciseNotes');if(load){load.addEventListener('change',function(){saved.load=this.value;saveDraft();},false);load.addEventListener('input',function(){saved.load=this.value;saveDraft();},false);}if(notes){notes.addEventListener('input',function(){saved.notes=this.value;saveDraft();},false);}for(i=0;i<saved.sets.length;i++){(function(n){var el=document.getElementById('reps'+n);if(el){el.addEventListener('input',function(){saved.sets[n].reps=this.value;saveDraft();},false);}}(i));}}
  function bindEditButtons(saved){var buttons=view.getElementsByTagName('button'),i,n;for(i=0;i<buttons.length;i++){if(buttons[i].getAttribute('data-edit')!==null){buttons[i].onclick=function(){n=parseInt(this.getAttribute('data-edit'),10);saved.sets[n].done=false;saved.sets[n].skipped=false;saveDraft();exerciseScreen();};}}}
  function saveFields(){var saved,el,i;if(!current||!document.getElementById('exerciseNotes')){return;}saved=current.exercises[currentExercise];el=document.getElementById('load')||document.getElementById('resistance');if(el){saved.load=el.value;}el=document.getElementById('exerciseNotes');if(el){saved.notes=el.value;}for(i=0;i<saved.sets.length;i++){el=document.getElementById('reps'+i);if(el){saved.sets[i].reps=el.value;}}saveDraft();}
  function pendingSet(){var sets=current.exercises[currentExercise].sets,i;for(i=0;i<sets.length;i++){if(!sets[i].done&&!sets[i].skipped){return i;}}return -1;}
  function completeSet(){var n=pendingSet(),input,ex=config.workouts[current.kind].exercises[currentExercise];if(n<0){alert('Tutte le serie sono già registrate.');return;}saveFields();input=document.getElementById('reps'+n);if(!current.exercises[currentExercise].sets[n].reps){if(input){input.focus();}alert('Inserisci prima le ripetizioni.');return;}prepareAudio();current.exercises[currentExercise].sets[n].done=true;saveDraft();lastAnnounced=-1;timerReturn=exerciseScreen;GymTimer.start(ex.rest);timerScreen();}
  function skipSet(){var n=pendingSet();if(n>=0){saveFields();current.exercises[currentExercise].sets[n].skipped=true;saveDraft();exerciseScreen();}}
  function finishExercise(){var sets=current.exercises[currentExercise].sets,i;saveFields();if(!confirm('Terminare questo esercizio e saltare le serie ancora vuote?')){return;}for(i=0;i<sets.length;i++){if(!sets[i].done){sets[i].skipped=true;}}if(currentExercise<config.workouts[current.kind].exercises.length-1){currentExercise++;saveDraft();exerciseScreen();}else{finishWorkout();}}
  function finishWorkout(){saveFields();if(!confirm('Terminare e salvare questo allenamento?')){return;}current.completed=true;current.notes=prompt('Note generali allenamento (facoltative):',current.notes||'')||'';GymStorage.addSession(current);current=null;alert('Allenamento salvato.');home();}

  function timerScreen(){var s=GymTimer.seconds();show('TIMER','<div class="timer-box"><div id="countdown" class="countdown'+(s<=10&&s>0?' urgent':'')+'">'+formatTime(s)+'</div><div id="timerState" class="muted">'+(GymTimer.isRunning()?'IN CORSO':'PRONTO')+'</div><div id="elapsed" class="elapsed">Trascorsi: '+formatTime(GymTimer.elapsed())+'</div><div class="timer-buttons"><button data-seconds="30">30 s</button><button data-seconds="60">60 s</button><button data-seconds="90">90 s</button><button data-seconds="120">120 s</button><button id="add15">+15 s</button><button id="pause">PAUSA</button><button id="reset">RESET</button><button id="skipTimer">SALTA</button></div></div>',true);var buttons=view.getElementsByTagName('button'),i;for(i=0;i<buttons.length;i++){if(buttons[i].getAttribute('data-seconds')){buttons[i].onclick=function(){prepareAudio();lastAnnounced=-1;GymTimer.start(this.getAttribute('data-seconds'));};}}bind('add15','click',function(){prepareAudio();GymTimer.add(15);});bind('pause','click',function(){prepareAudio();if(GymTimer.isRunning()){GymTimer.pause();this.innerHTML='RIPRENDI';}else{GymTimer.resume();this.innerHTML='PAUSA';}});bind('reset','click',function(){GymTimer.reset();lastAnnounced=-1;});bind('skipTimer','click',function(){GymTimer.skip();if(timerReturn){timerReturn();}});back.onclick=function(){if(timerReturn){timerReturn();}else{home();}};}
  function formatTime(s){var m=Math.floor(s/60),r=s%60;return ('0'+m).slice(-2)+':'+('0'+r).slice(-2);}
  function timerTick(s,running,elapsed){var el=document.getElementById('countdown'),st=document.getElementById('timerState'),et=document.getElementById('elapsed');if(el){el.innerHTML=formatTime(s);el.className='countdown'+(s<=10&&s>0?' urgent':'');}if(st){st.innerHTML=running?'IN CORSO':'IN PAUSA';}if(et){et.innerHTML='Trascorsi: '+formatTime(elapsed);}if(running&&(s===10||s===5||s===4||s===3||s===2||s===1)&&lastAnnounced!==s){lastAnnounced=s;beep(true);}}
  function timerDone(){beep(false);try{if(navigator.vibrate){navigator.vibrate([400,150,400]);}}catch(e){}flash.className='flash';setTimeout(function(){flash.className='flash hidden';},3000);}
  function prepareAudio(){try{var C=window.AudioContext||window.webkitAudioContext;if(!C){return;}if(!audioContext){audioContext=new C();}if(audioContext.state==='suspended'&&audioContext.resume){audioContext.resume();}}catch(e){}}
  function beep(shortBeep){try{var o,g,settings=GymStorage.settings(),freq=settings.soundType==='low'?440:(settings.soundType==='double'?660:880),length=shortBeep?130:700;if(!audioContext){return;}if(audioContext.state==='suspended'&&audioContext.resume){audioContext.resume();}o=audioContext.createOscillator();g=audioContext.createGain();o.connect(g);g.connect(audioContext.destination);o.frequency.value=freq;g.gain.value=(parseInt(settings.soundVolume,10)||0)/100;o.start(0);setTimeout(function(){try{o.stop(0);}catch(e){}},length);if(!shortBeep&&settings.soundType==='double'){setTimeout(function(){beep(true);},850);}}catch(e){}}

  function findLast(id){var sessions=GymStorage.read().sessions,i,j,s,e;for(i=sessions.length-1;i>=0;i--){s=sessions[i];for(j=0;j<s.exercises.length;j++){e=s.exercises[j];if(e.id===id){return {load:e.load||'',reps:(function(){var a=[],k;for(k=0;k<e.sets.length;k++){if(e.sets[k].done){a.push(e.sets[k].reps);}}return a;}())};}}}return null;}
  function history(){var d=GymStorage.read(),html='<h2>Storico</h2>',i,s;if(!d.sessions.length){html+='<div class="card">Nessun allenamento salvato.</div>';}for(i=d.sessions.length-1;i>=0;i--){s=d.sessions[i];html+='<button class="history-item" data-index="'+i+'">'+dateText(s.date)+' — '+esc(s.name)+'</button>';}show('STORICO',html,true);var b=view.getElementsByTagName('button');for(i=0;i<b.length;i++){b[i].onclick=function(){historyDetail(parseInt(this.getAttribute('data-index'),10));};}back.onclick=home;}
  function historyDetail(index){var s=GymStorage.read().sessions[index],html='<h2>'+dateText(s.date)+' — '+esc(s.name)+'</h2>',i,j,e,reps;for(i=0;i<s.exercises.length;i++){e=s.exercises[i];reps=[];for(j=0;j<e.sets.length;j++){if(e.sets[j].done){reps.push(e.sets[j].reps);}}html+='<div class="card"><h3>'+esc(e.name)+'</h3><div>'+esc(e.load||'—')+' · '+esc(reps.join(' / ')||'Nessuna serie')+'</div>'+(e.notes?'<div class="small muted">'+esc(e.notes)+'</div>':'')+'</div>';}if(s.notes){html+='<div class="card">Note: '+esc(s.notes)+'</div>';}show('DETTAGLIO',html,true);back.onclick=history;}
  function progress(){var all=[],k,w,i,last,html='<h2>Ultime prestazioni</h2>';for(k in config.workouts){if(config.workouts.hasOwnProperty(k)){w=config.workouts[k];for(i=0;i<w.exercises.length;i++){if(!contains(all,w.exercises[i].id)){all.push(w.exercises[i].id);last=findLast(w.exercises[i].id);html+='<div class="card"><h3>'+esc(w.exercises[i].name)+'</h3>'+(last?'<div>'+esc(last.load||'—')+' · '+esc(last.reps.join(' / '))+'</div>'+suggestion(w.exercises[i],last):'<div class="muted">Nessun dato</div>')+'</div>';}}}}show('PROGRESSI',html,true);back.onclick=home;}
  function suggestion(ex,last){var i;if(!last.reps.length){return '';}for(i=0;i<last.reps.length;i++){if(parseInt(last.reps[i],10)<ex.max){return '';}}return '<div class="hint small">Prossima volta prova ad aumentare il carico.</div>';}

  function settings(){var d=GymStorage.read(),s=d.settings;show('IMPOSTAZIONI',updateNotice()+'<div class="card"><h3>Versione</h3><div class="version">'+APP_VERSION+' · '+APP_DATE+'</div><button id="checkUpdate" style="width:100%;margin-top:12px">CONTROLLA AGGIORNAMENTI</button><div id="updateStatus" class="small muted"></div></div><div class="card"><h3>Allenamento</h3><label>Serie principali <select id="mainSets"><option value="3">3 serie</option><option value="2">2 serie</option></select></label></div><div class="card"><h3>Suono timer</h3><div class="field"><label>TIPO</label><select id="soundType"><option value="beep">Acuto</option><option value="low">Basso</option><option value="double">Doppio finale</option></select></div><div class="field"><label>VOLUME 0-100</label><input id="soundVolume" type="number" min="0" max="100" step="10" value="'+esc(s.soundVolume)+'"></div><button id="testSound">PROVA SUONO</button></div><div class="actions"><button id="export">ESPORTA DATI</button><button id="import">IMPORTA DATI</button></div><input id="fileInput" class="hidden" type="file" accept="application/json"><div class="small muted">I dati restano su questo dispositivo. Fai periodicamente un backup.</div>',true);document.getElementById('mainSets').value=String(s.mainSets||3);document.getElementById('soundType').value=s.soundType||'beep';bindUpdate();bind('mainSets','change',saveSettings);bind('soundType','change',saveSettings);bind('soundVolume','change',saveSettings);bind('testSound','click',function(){saveSettings();prepareAudio();beep(false);});bind('checkUpdate','click',checkUpdate);bind('export','click',exportData);bind('import','click',function(){document.getElementById('fileInput').click();});bind('fileInput','change',importData);back.onclick=home;}
  function saveSettings(){var s=GymStorage.settings(),el;s.mainSets=parseInt(document.getElementById('mainSets').value,10);s.soundType=document.getElementById('soundType').value;el=document.getElementById('soundVolume');s.soundVolume=Math.max(0,Math.min(100,parseInt(el.value,10)||0));GymStorage.settings(s);}
  function exportData(){var text=JSON.stringify(GymStorage.read(),null,2),blob,url,a;try{blob=new Blob([text],{type:'application/json'});url=(window.URL||window.webkitURL).createObjectURL(blob);a=document.createElement('a');a.href=url;a.download='gym-console-backup-'+APP_VERSION+'.json';document.body.appendChild(a);a.click();document.body.removeChild(a);setTimeout(function(){(window.URL||window.webkitURL).revokeObjectURL(url);},1000);}catch(e){prompt('Copia e salva questo backup:',text);}}
  function importData(evt){var file=evt.target.files[0],reader;if(!file){return;}reader=new FileReader();reader.onload=function(){var data;try{data=JSON.parse(reader.result);if(!data.sessions||!data.settings){throw new Error();}if(confirm('Sostituire tutti i dati attuali con il backup?')){GymStorage.replace(data);alert('Importazione completata.');settings();}}catch(e){alert('File di backup non valido.');}};reader.readAsText(file);}

  function watchRegistration(reg){registration=reg;if(reg.waiting){updateReady=true;}reg.addEventListener('updatefound',function(){var worker=reg.installing;if(worker){worker.addEventListener('statechange',function(){if(worker.state==='installed'&&navigator.serviceWorker.controller){updateReady=true;if(document.getElementById('view')){home();}}},false);}},false);}
  function checkUpdate(){var status=document.getElementById('updateStatus');if(status){status.innerHTML='Controllo in corso…';}if(!registration){if(status){status.innerHTML='Aggiornamenti automatici non disponibili in questa modalità.';}return;}registration.update().then(function(){setTimeout(function(){if(updateReady){settings();}else if(status){status.innerHTML='Hai già la versione più recente.';}},1000);},function(){if(status){status.innerHTML='Controllo non riuscito. Verifica la connessione.';}});}
  function applyUpdate(){if(registration&&registration.waiting){registration.waiting.postMessage({action:'skipWaiting'});}else{window.location.reload();}}

  GymTimer.configure(timerTick,timerDone);GymWorkouts.load(function(data){config=data;home();});
  if('serviceWorker' in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('service-worker.js').then(watchRegistration);},false);navigator.serviceWorker.addEventListener('controllerchange',function(){window.location.reload();},false);}
}());
